version: "3.7"

services:

  php:
    user: ${UID}:${GID}
    volumes:
      - .:/var/www
    working_dir: /var/www

  web:
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
    working_dir: /var/www

  node:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
    ports:
    - 8080:8080
    working_dir: /app
    command: tail -f /dev/null

  dusk:
    volumes:
      - .:/app
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/dusk/Dockerfile
    networks:
      - backend
    command: bash -c "
        /wait-for db:3306
        && php artisan migrate --env=dusk.local
        && php artisan dusk
      "
