name: CI

on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build infrastructure
      run: docker-compose --project-directory "$(pwd)" -f docker/docker-compose.yml build
    - name: Build source code
      run: docker-compose --project-directory "$(pwd)" -f docker/src/docker-compose.yml build
    - name: Build release
      run:  docker-compose --project-directory "$(pwd)" -f docker/docker-compose.yml -f docker/docker-compose.production.yml
    - name: Push docker image
      run: |
        echo ${TOKEN} | docker login -u ${USERNAME} --password-stdin
        docker-compose --project-directory "$(pwd)" \
          -f docker/docker-compose.yml \
          -f docker/docker-compose.production.yml \
          images push
        docker logout
