name: Status Check

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker images
        run: |
          cp .env.example .env
          source aliases.sh
          docker_compose_dev up -d
      - name: Install PHP packages
        run: source aliases.sh && docker_compose_dev exec -T php composer install --no-progress --no-ansi
      - name: Run db migrations
        run: |
          source aliases.sh
          docker_compose_dev exec -T php php artisan migrate
          docker_compose_dev exec -T php php artisan migrate --env=testing
          docker_compose_dev exec -T php php artisan migrate --env=dusk.local
      - name: Run unit, integration, and feature tests
        run: source aliases.sh && docker_compose_dev exec -T php php ./vendor/bin/phpunit
      - name: Jest
        run: |
          source aliases.sh
          docker_compose_dev exec -T node yarn install
          docker_compose_dev exec -T node yarn test
      - name: Run browser tests
        run: |
          source aliases.sh
          docker_compose_dev run --rm dusk php artisan dusk:chrome-driver 79
          sudo chown -R 82:82 .
          docker_compose_dev run --rm dusk php artisan dusk
      - name: Archive failed tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: Screenshots
          path: tests/Browser/screenshots
